/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HospitalIndexRouteImport } from './routes/hospital/index'
import { Route as HospitalDashRouteImport } from './routes/hospital/_dash'
import { Route as HospitalLoginRouteImport } from './routes/hospital/login'
import { Route as PatientIndexRouteImport } from './routes/patient/index'
import { Route as PatientDashRouteImport } from './routes/patient/_dash'
import { Route as PatientLoginRouteImport } from './routes/patient/login'
import { Route as HospitalDashAnalyticsRouteImport } from './routes/hospital/_dash/analytics'
import { Route as HospitalDashFollowUpsRouteImport } from './routes/hospital/_dash/follow-ups'
import { Route as HospitalDashHighRiskRouteImport } from './routes/hospital/_dash/high-risk'
import { Route as HospitalDashInterventionsRouteImport } from './routes/hospital/_dash/interventions'
import { Route as HospitalDashMedicationsRouteImport } from './routes/hospital/_dash/medications'
import { Route as HospitalDashOverviewRouteImport } from './routes/hospital/_dash/overview'
import { Route as HospitalDashPatientsRouteImport } from './routes/hospital/_dash/patients'
import { Route as HospitalDashRevenueRouteImport } from './routes/hospital/_dash/revenue'
import { Route as HospitalDashSettingsRouteImport } from './routes/hospital/_dash/settings'
import { Route as PatientDashAppointmentsRouteImport } from './routes/patient/_dash/appointments'
import { Route as PatientDashCareScoreRouteImport } from './routes/patient/_dash/care-score'
import { Route as PatientDashFamilyRouteImport } from './routes/patient/_dash/family'
import { Route as PatientDashHomeRouteImport } from './routes/patient/_dash/home'
import { Route as PatientDashMedicinesRouteImport } from './routes/patient/_dash/medicines'
import { Route as PatientDashMessagesRouteImport } from './routes/patient/_dash/messages'
import { Route as PatientDashProfileRouteImport } from './routes/patient/_dash/profile'
import { Route as PatientDashTestsRouteImport } from './routes/patient/_dash/tests'
import { Route as HospitalDashPatientIdRouteImport } from './routes/hospital/_dash/patient.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalIndexRoute = HospitalIndexRouteImport.update({
  id: '/hospital/',
  path: '/hospital/',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalDashRoute = HospitalDashRouteImport.update({
  id: '/hospital/_dash',
  path: '/hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalLoginRoute = HospitalLoginRouteImport.update({
  id: '/hospital/login',
  path: '/hospital/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/patient/',
  path: '/patient/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientDashRoute = PatientDashRouteImport.update({
  id: '/patient/_dash',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientLoginRoute = PatientLoginRouteImport.update({
  id: '/patient/login',
  path: '/patient/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalDashAnalyticsRoute = HospitalDashAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => HospitalDashRoute,
} as any)
const HospitalDashFollowUpsRoute = HospitalDashFollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => HospitalDashRoute,
} as any)
const HospitalDashHighRiskRoute = HospitalDashHighRiskRouteImport.update({
  id: '/high-risk',
  path: '/high-risk',
  getParentRoute: () => HospitalDashRoute,
} as any)
const HospitalDashInterventionsRoute =
  HospitalDashInterventionsRouteImport.update({
    id: '/interventions',
    path: '/interventions',
    getParentRoute: () => HospitalDashRoute,
  } as any)
const HospitalDashMedicationsRoute = HospitalDashMedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => HospitalDashRoute,
} as any)
const HospitalDashOverviewRoute = HospitalDashOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => HospitalDashRoute,
} as any)
const HospitalDashPatientsRoute = HospitalDashPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => HospitalDashRoute,
} as any)
const HospitalDashRevenueRoute = HospitalDashRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => HospitalDashRoute,
} as any)
const HospitalDashSettingsRoute = HospitalDashSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HospitalDashRoute,
} as any)
const PatientDashAppointmentsRoute = PatientDashAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PatientDashRoute,
} as any)
const PatientDashCareScoreRoute = PatientDashCareScoreRouteImport.update({
  id: '/care-score',
  path: '/care-score',
  getParentRoute: () => PatientDashRoute,
} as any)
const PatientDashFamilyRoute = PatientDashFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => PatientDashRoute,
} as any)
const PatientDashHomeRoute = PatientDashHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => PatientDashRoute,
} as any)
const PatientDashMedicinesRoute = PatientDashMedicinesRouteImport.update({
  id: '/medicines',
  path: '/medicines',
  getParentRoute: () => PatientDashRoute,
} as any)
const PatientDashMessagesRoute = PatientDashMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PatientDashRoute,
} as any)
const PatientDashProfileRoute = PatientDashProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PatientDashRoute,
} as any)
const PatientDashTestsRoute = PatientDashTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => PatientDashRoute,
} as any)
const HospitalDashPatientIdRoute = HospitalDashPatientIdRouteImport.update({
  id: '/patient/$id',
  path: '/patient/$id',
  getParentRoute: () => HospitalDashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hospital': typeof HospitalDashRouteWithChildren
  '/hospital/login': typeof HospitalLoginRoute
  '/patient': typeof PatientDashRouteWithChildren
  '/patient/login': typeof PatientLoginRoute
  '/hospital/': typeof HospitalIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/hospital/analytics': typeof HospitalDashAnalyticsRoute
  '/hospital/follow-ups': typeof HospitalDashFollowUpsRoute
  '/hospital/high-risk': typeof HospitalDashHighRiskRoute
  '/hospital/interventions': typeof HospitalDashInterventionsRoute
  '/hospital/medications': typeof HospitalDashMedicationsRoute
  '/hospital/overview': typeof HospitalDashOverviewRoute
  '/hospital/patients': typeof HospitalDashPatientsRoute
  '/hospital/revenue': typeof HospitalDashRevenueRoute
  '/hospital/settings': typeof HospitalDashSettingsRoute
  '/patient/appointments': typeof PatientDashAppointmentsRoute
  '/patient/care-score': typeof PatientDashCareScoreRoute
  '/patient/family': typeof PatientDashFamilyRoute
  '/patient/home': typeof PatientDashHomeRoute
  '/patient/medicines': typeof PatientDashMedicinesRoute
  '/patient/messages': typeof PatientDashMessagesRoute
  '/patient/profile': typeof PatientDashProfileRoute
  '/patient/tests': typeof PatientDashTestsRoute
  '/hospital/patient/$id': typeof HospitalDashPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hospital': typeof HospitalIndexRoute
  '/hospital/login': typeof HospitalLoginRoute
  '/patient': typeof PatientIndexRoute
  '/patient/login': typeof PatientLoginRoute
  '/hospital/analytics': typeof HospitalDashAnalyticsRoute
  '/hospital/follow-ups': typeof HospitalDashFollowUpsRoute
  '/hospital/high-risk': typeof HospitalDashHighRiskRoute
  '/hospital/interventions': typeof HospitalDashInterventionsRoute
  '/hospital/medications': typeof HospitalDashMedicationsRoute
  '/hospital/overview': typeof HospitalDashOverviewRoute
  '/hospital/patients': typeof HospitalDashPatientsRoute
  '/hospital/revenue': typeof HospitalDashRevenueRoute
  '/hospital/settings': typeof HospitalDashSettingsRoute
  '/patient/appointments': typeof PatientDashAppointmentsRoute
  '/patient/care-score': typeof PatientDashCareScoreRoute
  '/patient/family': typeof PatientDashFamilyRoute
  '/patient/home': typeof PatientDashHomeRoute
  '/patient/medicines': typeof PatientDashMedicinesRoute
  '/patient/messages': typeof PatientDashMessagesRoute
  '/patient/profile': typeof PatientDashProfileRoute
  '/patient/tests': typeof PatientDashTestsRoute
  '/hospital/patient/$id': typeof HospitalDashPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hospital/_dash': typeof HospitalDashRouteWithChildren
  '/hospital/login': typeof HospitalLoginRoute
  '/patient/_dash': typeof PatientDashRouteWithChildren
  '/patient/login': typeof PatientLoginRoute
  '/hospital/': typeof HospitalIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/hospital/_dash/analytics': typeof HospitalDashAnalyticsRoute
  '/hospital/_dash/follow-ups': typeof HospitalDashFollowUpsRoute
  '/hospital/_dash/high-risk': typeof HospitalDashHighRiskRoute
  '/hospital/_dash/interventions': typeof HospitalDashInterventionsRoute
  '/hospital/_dash/medications': typeof HospitalDashMedicationsRoute
  '/hospital/_dash/overview': typeof HospitalDashOverviewRoute
  '/hospital/_dash/patients': typeof HospitalDashPatientsRoute
  '/hospital/_dash/revenue': typeof HospitalDashRevenueRoute
  '/hospital/_dash/settings': typeof HospitalDashSettingsRoute
  '/patient/_dash/appointments': typeof PatientDashAppointmentsRoute
  '/patient/_dash/care-score': typeof PatientDashCareScoreRoute
  '/patient/_dash/family': typeof PatientDashFamilyRoute
  '/patient/_dash/home': typeof PatientDashHomeRoute
  '/patient/_dash/medicines': typeof PatientDashMedicinesRoute
  '/patient/_dash/messages': typeof PatientDashMessagesRoute
  '/patient/_dash/profile': typeof PatientDashProfileRoute
  '/patient/_dash/tests': typeof PatientDashTestsRoute
  '/hospital/_dash/patient/$id': typeof HospitalDashPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hospital'
    | '/hospital/login'
    | '/patient'
    | '/patient/login'
    | '/hospital/'
    | '/patient/'
    | '/hospital/analytics'
    | '/hospital/follow-ups'
    | '/hospital/high-risk'
    | '/hospital/interventions'
    | '/hospital/medications'
    | '/hospital/overview'
    | '/hospital/patients'
    | '/hospital/revenue'
    | '/hospital/settings'
    | '/patient/appointments'
    | '/patient/care-score'
    | '/patient/family'
    | '/patient/home'
    | '/patient/medicines'
    | '/patient/messages'
    | '/patient/profile'
    | '/patient/tests'
    | '/hospital/patient/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hospital'
    | '/hospital/login'
    | '/patient'
    | '/patient/login'
    | '/hospital/analytics'
    | '/hospital/follow-ups'
    | '/hospital/high-risk'
    | '/hospital/interventions'
    | '/hospital/medications'
    | '/hospital/overview'
    | '/hospital/patients'
    | '/hospital/revenue'
    | '/hospital/settings'
    | '/patient/appointments'
    | '/patient/care-score'
    | '/patient/family'
    | '/patient/home'
    | '/patient/medicines'
    | '/patient/messages'
    | '/patient/profile'
    | '/patient/tests'
    | '/hospital/patient/$id'
  id:
    | '__root__'
    | '/'
    | '/hospital/_dash'
    | '/hospital/login'
    | '/patient/_dash'
    | '/patient/login'
    | '/hospital/'
    | '/patient/'
    | '/hospital/_dash/analytics'
    | '/hospital/_dash/follow-ups'
    | '/hospital/_dash/high-risk'
    | '/hospital/_dash/interventions'
    | '/hospital/_dash/medications'
    | '/hospital/_dash/overview'
    | '/hospital/_dash/patients'
    | '/hospital/_dash/revenue'
    | '/hospital/_dash/settings'
    | '/patient/_dash/appointments'
    | '/patient/_dash/care-score'
    | '/patient/_dash/family'
    | '/patient/_dash/home'
    | '/patient/_dash/medicines'
    | '/patient/_dash/messages'
    | '/patient/_dash/profile'
    | '/patient/_dash/tests'
    | '/hospital/_dash/patient/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HospitalDashRoute: typeof HospitalDashRouteWithChildren
  HospitalLoginRoute: typeof HospitalLoginRoute
  PatientDashRoute: typeof PatientDashRouteWithChildren
  PatientLoginRoute: typeof PatientLoginRoute
  HospitalIndexRoute: typeof HospitalIndexRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/': {
      id: '/hospital/'
      path: '/hospital'
      fullPath: '/hospital/'
      preLoaderRoute: typeof HospitalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/_dash': {
      id: '/hospital/_dash'
      path: '/hospital'
      fullPath: '/hospital'
      preLoaderRoute: typeof HospitalDashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/login': {
      id: '/hospital/login'
      path: '/hospital/login'
      fullPath: '/hospital/login'
      preLoaderRoute: typeof HospitalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/patient'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/_dash': {
      id: '/patient/_dash'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientDashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/login': {
      id: '/patient/login'
      path: '/patient/login'
      fullPath: '/patient/login'
      preLoaderRoute: typeof PatientLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/_dash/analytics': {
      id: '/hospital/_dash/analytics'
      path: '/analytics'
      fullPath: '/hospital/analytics'
      preLoaderRoute: typeof HospitalDashAnalyticsRouteImport
      parentRoute: typeof HospitalDashRoute
    }
    '/hospital/_dash/follow-ups': {
      id: '/hospital/_dash/follow-ups'
      path: '/follow-ups'
      fullPath: '/hospital/follow-ups'
      preLoaderRoute: typeof HospitalDashFollowUpsRouteImport
      parentRoute: typeof HospitalDashRoute
    }
    '/hospital/_dash/high-risk': {
      id: '/hospital/_dash/high-risk'
      path: '/high-risk'
      fullPath: '/hospital/high-risk'
      preLoaderRoute: typeof HospitalDashHighRiskRouteImport
      parentRoute: typeof HospitalDashRoute
    }
    '/hospital/_dash/interventions': {
      id: '/hospital/_dash/interventions'
      path: '/interventions'
      fullPath: '/hospital/interventions'
      preLoaderRoute: typeof HospitalDashInterventionsRouteImport
      parentRoute: typeof HospitalDashRoute
    }
    '/hospital/_dash/medications': {
      id: '/hospital/_dash/medications'
      path: '/medications'
      fullPath: '/hospital/medications'
      preLoaderRoute: typeof HospitalDashMedicationsRouteImport
      parentRoute: typeof HospitalDashRoute
    }
    '/hospital/_dash/overview': {
      id: '/hospital/_dash/overview'
      path: '/overview'
      fullPath: '/hospital/overview'
      preLoaderRoute: typeof HospitalDashOverviewRouteImport
      parentRoute: typeof HospitalDashRoute
    }
    '/hospital/_dash/patients': {
      id: '/hospital/_dash/patients'
      path: '/patients'
      fullPath: '/hospital/patients'
      preLoaderRoute: typeof HospitalDashPatientsRouteImport
      parentRoute: typeof HospitalDashRoute
    }
    '/hospital/_dash/revenue': {
      id: '/hospital/_dash/revenue'
      path: '/revenue'
      fullPath: '/hospital/revenue'
      preLoaderRoute: typeof HospitalDashRevenueRouteImport
      parentRoute: typeof HospitalDashRoute
    }
    '/hospital/_dash/settings': {
      id: '/hospital/_dash/settings'
      path: '/settings'
      fullPath: '/hospital/settings'
      preLoaderRoute: typeof HospitalDashSettingsRouteImport
      parentRoute: typeof HospitalDashRoute
    }
    '/patient/_dash/appointments': {
      id: '/patient/_dash/appointments'
      path: '/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientDashAppointmentsRouteImport
      parentRoute: typeof PatientDashRoute
    }
    '/patient/_dash/care-score': {
      id: '/patient/_dash/care-score'
      path: '/care-score'
      fullPath: '/patient/care-score'
      preLoaderRoute: typeof PatientDashCareScoreRouteImport
      parentRoute: typeof PatientDashRoute
    }
    '/patient/_dash/family': {
      id: '/patient/_dash/family'
      path: '/family'
      fullPath: '/patient/family'
      preLoaderRoute: typeof PatientDashFamilyRouteImport
      parentRoute: typeof PatientDashRoute
    }
    '/patient/_dash/home': {
      id: '/patient/_dash/home'
      path: '/home'
      fullPath: '/patient/home'
      preLoaderRoute: typeof PatientDashHomeRouteImport
      parentRoute: typeof PatientDashRoute
    }
    '/patient/_dash/medicines': {
      id: '/patient/_dash/medicines'
      path: '/medicines'
      fullPath: '/patient/medicines'
      preLoaderRoute: typeof PatientDashMedicinesRouteImport
      parentRoute: typeof PatientDashRoute
    }
    '/patient/_dash/messages': {
      id: '/patient/_dash/messages'
      path: '/messages'
      fullPath: '/patient/messages'
      preLoaderRoute: typeof PatientDashMessagesRouteImport
      parentRoute: typeof PatientDashRoute
    }
    '/patient/_dash/profile': {
      id: '/patient/_dash/profile'
      path: '/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientDashProfileRouteImport
      parentRoute: typeof PatientDashRoute
    }
    '/patient/_dash/tests': {
      id: '/patient/_dash/tests'
      path: '/tests'
      fullPath: '/patient/tests'
      preLoaderRoute: typeof PatientDashTestsRouteImport
      parentRoute: typeof PatientDashRoute
    }
    '/hospital/_dash/patient/$id': {
      id: '/hospital/_dash/patient/$id'
      path: '/patient/$id'
      fullPath: '/hospital/patient/$id'
      preLoaderRoute: typeof HospitalDashPatientIdRouteImport
      parentRoute: typeof HospitalDashRoute
    }
  }
}

interface HospitalDashRouteChildren {
  HospitalDashAnalyticsRoute: typeof HospitalDashAnalyticsRoute
  HospitalDashFollowUpsRoute: typeof HospitalDashFollowUpsRoute
  HospitalDashHighRiskRoute: typeof HospitalDashHighRiskRoute
  HospitalDashInterventionsRoute: typeof HospitalDashInterventionsRoute
  HospitalDashMedicationsRoute: typeof HospitalDashMedicationsRoute
  HospitalDashOverviewRoute: typeof HospitalDashOverviewRoute
  HospitalDashPatientsRoute: typeof HospitalDashPatientsRoute
  HospitalDashRevenueRoute: typeof HospitalDashRevenueRoute
  HospitalDashSettingsRoute: typeof HospitalDashSettingsRoute
  HospitalDashPatientIdRoute: typeof HospitalDashPatientIdRoute
}

const HospitalDashRouteChildren: HospitalDashRouteChildren = {
  HospitalDashAnalyticsRoute: HospitalDashAnalyticsRoute,
  HospitalDashFollowUpsRoute: HospitalDashFollowUpsRoute,
  HospitalDashHighRiskRoute: HospitalDashHighRiskRoute,
  HospitalDashInterventionsRoute: HospitalDashInterventionsRoute,
  HospitalDashMedicationsRoute: HospitalDashMedicationsRoute,
  HospitalDashOverviewRoute: HospitalDashOverviewRoute,
  HospitalDashPatientsRoute: HospitalDashPatientsRoute,
  HospitalDashRevenueRoute: HospitalDashRevenueRoute,
  HospitalDashSettingsRoute: HospitalDashSettingsRoute,
  HospitalDashPatientIdRoute: HospitalDashPatientIdRoute,
}

const HospitalDashRouteWithChildren = HospitalDashRoute._addFileChildren(
  HospitalDashRouteChildren,
)

interface PatientDashRouteChildren {
  PatientDashAppointmentsRoute: typeof PatientDashAppointmentsRoute
  PatientDashCareScoreRoute: typeof PatientDashCareScoreRoute
  PatientDashFamilyRoute: typeof PatientDashFamilyRoute
  PatientDashHomeRoute: typeof PatientDashHomeRoute
  PatientDashMedicinesRoute: typeof PatientDashMedicinesRoute
  PatientDashMessagesRoute: typeof PatientDashMessagesRoute
  PatientDashProfileRoute: typeof PatientDashProfileRoute
  PatientDashTestsRoute: typeof PatientDashTestsRoute
}

const PatientDashRouteChildren: PatientDashRouteChildren = {
  PatientDashAppointmentsRoute: PatientDashAppointmentsRoute,
  PatientDashCareScoreRoute: PatientDashCareScoreRoute,
  PatientDashFamilyRoute: PatientDashFamilyRoute,
  PatientDashHomeRoute: PatientDashHomeRoute,
  PatientDashMedicinesRoute: PatientDashMedicinesRoute,
  PatientDashMessagesRoute: PatientDashMessagesRoute,
  PatientDashProfileRoute: PatientDashProfileRoute,
  PatientDashTestsRoute: PatientDashTestsRoute,
}

const PatientDashRouteWithChildren = PatientDashRoute._addFileChildren(
  PatientDashRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HospitalDashRoute: HospitalDashRouteWithChildren,
  HospitalLoginRoute: HospitalLoginRoute,
  PatientDashRoute: PatientDashRouteWithChildren,
  PatientLoginRoute: PatientLoginRoute,
  HospitalIndexRoute: HospitalIndexRoute,
  PatientIndexRoute: PatientIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
