/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HospitalIndexRouteImport } from './routes/hospital/index'
import { Route as HospitalDashRouteImport } from './routes/hospital/_dash'
import { Route as HospitalLoginRouteImport } from './routes/hospital/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalIndexRoute = HospitalIndexRouteImport.update({
  id: '/hospital/',
  path: '/hospital/',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalDashRoute = HospitalDashRouteImport.update({
  id: '/hospital/_dash',
  path: '/hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalLoginRoute = HospitalLoginRouteImport.update({
  id: '/hospital/login',
  path: '/hospital/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hospital': typeof HospitalDashRoute
  '/hospital/login': typeof HospitalLoginRoute
  '/hospital/': typeof HospitalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hospital': typeof HospitalIndexRoute
  '/hospital/login': typeof HospitalLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hospital/_dash': typeof HospitalDashRoute
  '/hospital/login': typeof HospitalLoginRoute
  '/hospital/': typeof HospitalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hospital' | '/hospital/login' | '/hospital/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hospital' | '/hospital/login'
  id: '__root__' | '/' | '/hospital/_dash' | '/hospital/login' | '/hospital/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HospitalDashRoute: typeof HospitalDashRoute
  HospitalLoginRoute: typeof HospitalLoginRoute
  HospitalIndexRoute: typeof HospitalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/': {
      id: '/hospital/'
      path: '/hospital'
      fullPath: '/hospital/'
      preLoaderRoute: typeof HospitalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/_dash': {
      id: '/hospital/_dash'
      path: '/hospital'
      fullPath: '/hospital'
      preLoaderRoute: typeof HospitalDashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/login': {
      id: '/hospital/login'
      path: '/hospital/login'
      fullPath: '/hospital/login'
      preLoaderRoute: typeof HospitalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HospitalDashRoute: HospitalDashRoute,
  HospitalLoginRoute: HospitalLoginRoute,
  HospitalIndexRoute: HospitalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
